name: Gerar e Publicar ZIP como Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar o ZIP da pasta `config`
        run: |
          zip -r config_files.zip config_files/

      - name: Publicar release "latest" com o .zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Files
          files: config_files.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
