name: Compactar Pasta em ZIP

on:
  push:
    branches:
      - main

jobs:
  zip-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Compactar pasta em ZIP
        run: |
          cd config_files
          zip -r ../nconfig_files.zip .

      - name: Upload do ZIP como artefato
        uses: actions/upload-artifact@v4
        with:
          name: config_files
          path: config_files.zip
